language: go
sudo: required
go:
  - 1.11.x

before_install:

script:
  - make build
  - make test

after_success:
  # send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash) -f "!mock.go"
